## Notebook for pattern based analysis

The experiment is conducted on the sampled challenge set datasets shared by zhiguo. We generate the MV3 and MV4 model prediction using CSDS

In [34]:
import pandas as pd

In [8]:
MV4_model_prediction = "AllDetails.2020_02_27_14_34_48_mv4_target_set_sample_QueryPatterns_all.tsv"
MV3_model_prediction = "AllDetails.2020_02_27_14_47_04_mv3_target_set_sample_QueryPatterns_all.tsv"

df_mv4 = pd.read_csv(MV4_model_prediction, sep='\t', header=0, encoding = "utf-8")
df_mv3 = pd.read_csv(MV3_model_prediction, sep='\t', header=0, encoding = "utf-8")

In [10]:
df_mv4

                                                Pattern  Freq  Wrong  Accuracy
0                                message <contact_name>    22     12  0.454545
1                      message <contact_name> <message>    16      5  0.687500
2                                     message <message>    13     10  0.230769
3                      send a message to <contact_name>    12      6  0.500000
4                       say <message> to <contact_name>    11     11  0.000000
5              cortana send a message to <contact_name>    10      4  0.600000
6      cortana send message to <contact_name> <message>    10      3  0.700000
7     hey cortana message my <order_ref> meeting tha...    10      0  1.000000
8                             message to <contact_name>    10      1  0.900000
9            send a message to <contact_name> <message>     9      4  0.555556
10        hey cortana message my meeting that <message>     8      1  0.875000
11                             send a message <message>     8      6  0.250000
12                cortana tell <contact_name> <message>     7      0  1.000000
13    hey cortana, send a message to <contact_name> ...     7      2  0.714286
14                 message my <time> meeting. <message>     7      0  1.000000
15       message. my <order_ref> meeting that <message>     7      0  1.000000
16                         ask <contact_name> <message>     6      2  0.666667
17                can you send <contact_name> a message     6      0  1.000000
18     can you tell my <relationship_name> to <message>     6      1  0.833333
19                       cortana message <contact_name>     6      1  0.833333
20               cortana send message to <contact_name>     6      1  0.833333
21                          cortana text <contact_name>     6      1  0.833333
22    hey cortana message <contact_name> that <message>     6      0  1.000000
23                   hey cortana message <contact_name>     6      1  0.833333
24    hey cortana message my <time> meeting that <me...     6      0  1.000000
25         hey cortana send a message to <contact_name>     6      0  1.000000
26            hey cortana send <contact_name> a message     6      2  0.666667
27           hey cortana send message to <contact_name>     6      1  0.833333
28        hey cortana, send a message to <contact_name>     6      1  0.833333
29    hey cortana. send message to <meeting_title> m...     6      3  0.500000
...                                                 ...   ...    ...       ...
1746                              send a message to a 2     1      1  0.000000
1747       send a message to a <contact_name> <message>     1      0  1.000000
1748                           send a message to a girl     1      1  0.000000
1749                        send a message to a meeting     1      0  1.000000
1750  send a message to <contact_name> <source_platf...     1      1  0.000000
1751  send a message to <contact_name> . that <message>     1      0  1.000000
1752  send a message to <contact_name> hey cortana s...     1      1  0.000000
1753  send a message to <contact_name> that / <message>     1      1  0.000000
1754  send a message to <contact_name> <destination_...     1      0  1.000000
1755  send a message to <contact_name> and <contact_...     1      0  1.000000
1756  send a message to <contact_name> &apos;s name ...     1      0  1.000000
1757  send a message to <contact_name> in <source_pl...     1      1  0.000000
1758                              send a message to all     1      1  0.000000
1759  send a message to all attendees from my <order...     1      1  0.000000
1760                        send a message to <message>     1      1  0.000000
1761              send a message to <contact_name> from     1      1  0.000000
1762                              send a message to and     1      0  1.000000
1763               send a message to and <contact_name>     1      0  1.000000
1764                      send a message to anything to     1      0  1.000000
1765  send a message to <contact_name> on my <time> ...     1      1  0.000000
1766  send a message to <contact_name> at <time> <me...     1      1  0.000000
1767                    send a message to ask <message>     1      1  0.000000
1768                send a message to at <time> meeting     1      0  1.000000
1769  send a message to <contact_name> &apos;saying....     1      0  1.000000
1770                send a message to <contact_name> to     1      0  1.000000
1771                send a message to <contact_name> on     1      0  1.000000
1772  send a message to <contact_name> telling him t...     1      0  1.000000
1773          send a message to <meeting_title> meeting     1      1  0.000000
1774  send a message to <contact_name> , saying <mes...     1      0  1.000000
1775  send a message to <relationship_name> <contact...     1      1  0.000000

[1776 rows x 4 columns]

In [13]:
df_left = pd.merge(df_mv3, df_mv4, on='Pattern', how='left',suffixes=('_mv3','_mv4'))

,Pattern,Freq_mv3,Wrong_mv3,Accuracy_mv3,Freq_mv4,Wrong_mv4,Accuracy_mv4
0,message <contact_name>,22,12,0.454545,22.0,12.0,0.454545
1,message <contact_name> <message>,16,11,0.312500,16.0,5.0,0.687500
2,message <message>,13,8,0.384615,13.0,10.0,0.230769
3,send a message to <contact_name>,12,12,0.000000,12.0,6.0,0.500000
4,say <message> to <contact_name>,11,11,0.000000,11.0,11.0,0.000000
5,cortana send a message to <contact_name>,10,3,0.700000,10.0,4.0,0.600000
6,cortana send message to <contact_name> <message>,10,4,0.600000,10.0,3.0,0.700000
7,hey cortana message my <order_ref> meeting tha...,10,0,1.000000,10.0,0.0,1.000000
8,message to <contact_name>,10,4,0.600000,10.0,1.0,0.900000
9,send a message to <contact_name> <message>,9,5,0.444444,9.0,4.0,0.555556
10,hey cortana message my meeting that <message>,8,1,0.875000,8.0,1.0,0.875000
11,send a message <message>,8,4,0.500000,8.0,6.0,0.250000
12,cortana tell <contact_name> <message>,7,1,0.857143,7.0,0.0,1.000000
13,"hey cortana, send a message to <contact_name> ...",7,1,0.857143,7.0,2.0,0.714286
14,message my <time> meeting. <message>,7,1,0.857143,7.0,0.0,1.000000
15,message. my <order_ref> meeting that <message>,7,0,1.000000,7.0,0.0,1.000000
16,ask <contact_name> <message>,6,3,0.500000,6.0,2.0,0.666667
17,can you send <contact_name> a message,6,0,1.000000,6.0,0.0,1.000000
18,can you tell my <relationship_name> to <message>,6,2,0.666667,6.0,1.0,0.833333
19,cortana message <contact_name>,6,1,0.833333,6.0,1.0,0.833333
20,cortana send message to <contact_name>,6,1,0.833333,6.0,1.0,0.833333
21,cortana text <contact_name>,6,1,0.833333,6.0,1.0,0.833333
22,hey cortana message <contact_name> that <message>,6,0,1.000000,6.0,0.0,1.000000
23,hey cortana message <contact_name>,6,1,0.833333,6.0,1.0,0.833333
24,hey cortana message my <time> meeting that <me...,6,0,1.000000,6.0,0.0,1.000000
25,hey cortana send a message to <contact_name>,6,2,0.666667,6.0,0.0,1.000000
26,hey cortana send <contact_name> a message,6,1,0.833333,6.0,2.0,0.666667
27,hey cortana send message to <contact_name>,6,1,0.833333,6.0,1.0,0.833333
28,"hey cortana, send a message to <contact_name>",6,1,0.833333,6.0,1.0,0.833333
29,hey cortana. send message to <meeting_title> m...,6,3,0.500000,6.0,3.0,0.500000
...,...,...,...,...,...,...,...
1749,send a message to a 2,1,1,0.000000,1.0,1.0,0.000000
1750,send a message to a <contact_name> <message>,1,0,1.000000,1.0,0.0,1.000000
1751,send a message to a girl,1,1,0.000000,1.0,1.0,0.000000
1752,send a message to a meeting,1,0,1.000000,1.0,0.0,1.000000
1753,send a message to <contact_name> <source_platf...,1,1,0.000000,1.0,1.0,0.000000
1754,send a message to <contact_name> . that <message>,1,0,1.000000,1.0,0.0,1.000000
1755,send a message to <contact_name> hey cortana s...,1,1,0.000000,1.0,1.0,0.000000
1756,send a message to <contact_name> that / <message>,1,0,1.000000,1.0,1.0,0.000000
1757,send a message to <contact_name> <destination_...,1,0,1.000000,1.0,0.0,1.000000
1758,send a message to <contact_name> and <contact_...,1,0,1.000000,1.0,0.0,1.000000
1759,send a message to <contact_name> &apos;s name ...,1,0,1.000000,1.0,0.0,1.000000
1760,send a message to <contact_name> in <source_pl...,1,1,0.000000,1.0,1.0,0.000000
1761,send a message to all,1,0,1.000000,1.0,1.0,0.000000
1762,send a message to all attendees from my <order...,1,1,0.000000,1.0,1.0,0.000000
1763,send a message to <message>,1,1,0.000000,1.0,1.0,0.000000
1764,send a message to <contact_name> from,1,1,0.000000,1.0,1.0,0.000000
1765,send a message to and,1,0,1.000000,1.0,0.0,1.000000
1766,send a message to and <contact_name>,1,0,1.000000,1.0,0.0,1.000000
1767,send a message to anything to,1,1,0.000000,1.0,0.0,1.000000
1768,send a message to <contact_name> on my <time> ...,1,1,0.000000,1.0,1.0,0.000000
1769,send a message to <contact_name> at <time> <me...,1,1,0.000000,1.0,1.0,0.000000
1770,send a message to ask <message>,1,0,1.000000,1.0,1.0,0.000000
1771,send a message to at <time> meeting,1,0,1.000000,1.0,0.0,1.000000
1772,send a message to <contact_name> &apos;saying....,1,0,1.000000,1.0,0.0,1.000000
1773,send a message to <contact_name> to,1,0,1.000000,1.0,0.0,1.000000
1774,send a message to <contact_name> on,1,0,1.000000,1.0,0.0,1.000000
1775,send a message to <contact_name> telling him t...,1,0,1.000000,1.0,0.0,1.000000
1776,send a message to <meeting_title> meeting,1,0,1.000000,1.0,1.0,0.000000
1777,"send a message to <contact_name> , saying <mes...",1,0,1.000000,1.0,0.0,1.000000
1778,send a message to <relationship_name> <contact...,1,1,0.000000,1.0,1.0,0.000000

## For top patterns

In [38]:


df_left_high = df_left[df_left['Freq_mv3']>=6]

df_left_filter = df_left_high[['Pattern','Freq_mv3','Accuracy_mv3','Accuracy_mv4']]
df_left_filter_mv3win = df_left_filter[df_left_filter['Accuracy_mv3']>df_left_filter['Accuracy_mv4']]
df_left_filter_mv4win = df_left_filter[df_left_filter['Accuracy_mv3']<df_left_filter['Accuracy_mv4']]
df_on_par = df_left_filter[df_left_filter['Accuracy_mv3']==df_left_filter['Accuracy_mv4']]
print (len(df_left_filter_mv3win),len(df_left_filter_mv4win),len(df_on_par))
df_left_filter_mv4win

7 12 19

,Pattern,Freq_mv3,Accuracy_mv3,Accuracy_mv4
1,message <contact_name> <message>,16,0.312500,0.687500
3,send a message to <contact_name>,12,0.000000,0.500000
6,cortana send message to <contact_name> <message>,10,0.600000,0.700000
8,message to <contact_name>,10,0.600000,0.900000
9,send a message to <contact_name> <message>,9,0.444444,0.555556
12,cortana tell <contact_name> <message>,7,0.857143,1.000000
14,message my <time> meeting. <message>,7,0.857143,1.000000
16,ask <contact_name> <message>,6,0.500000,0.666667
18,can you tell my <relationship_name> to <message>,6,0.666667,0.833333
25,hey cortana send a message to <contact_name>,6,0.666667,1.000000
33,message. <contact_name> <message>,6,0.833333,1.000000
36,send a message <contact_name>,6,0.833333,1.000000

In [37]:
df_left_filter_mv3win

,Pattern,Freq_mv3,Accuracy_mv3,Accuracy_mv4
2,message <message>,13,0.384615,0.230769
5,cortana send a message to <contact_name>,10,0.700000,0.600000
11,send a message <message>,8,0.500000,0.250000
13,"hey cortana, send a message to <contact_name> ...",7,0.857143,0.714286
26,hey cortana send <contact_name> a message,6,0.833333,0.666667
34,message. my <order_ref> meeting <message>,6,0.833333,0.666667
37,send a message on <source_platform>,6,1.000000,0.833333

In [39]:
df_on_par

,Pattern,Freq_mv3,Accuracy_mv3,Accuracy_mv4
0,message <contact_name>,22,0.454545,0.454545
4,say <message> to <contact_name>,11,0.000000,0.000000
7,hey cortana message my <order_ref> meeting tha...,10,1.000000,1.000000
10,hey cortana message my meeting that <message>,8,0.875000,0.875000
15,message. my <order_ref> meeting that <message>,7,1.000000,1.000000
17,can you send <contact_name> a message,6,1.000000,1.000000
19,cortana message <contact_name>,6,0.833333,0.833333
20,cortana send message to <contact_name>,6,0.833333,0.833333
21,cortana text <contact_name>,6,0.833333,0.833333
22,hey cortana message <contact_name> that <message>,6,1.000000,1.000000
23,hey cortana message <contact_name>,6,0.833333,0.833333
24,hey cortana message my <time> meeting that <me...,6,1.000000,1.000000
27,hey cortana send message to <contact_name>,6,0.833333,0.833333
28,"hey cortana, send a message to <contact_name>",6,0.833333,0.833333
29,hey cortana. send message to <meeting_title> m...,6,0.500000,0.500000
30,message everyone on my <order_ref> meeting tha...,6,1.000000,1.000000
31,message my meeting that <message>,6,1.000000,1.000000
32,message the meeting that <message>,6,1.000000,1.000000
35,reply to <contact_name>,6,0.833333,0.833333

## For tail patterns

In [40]:

df_left_high = df_left[df_left['Freq_mv3']<6]

df_left_filter = df_left_high[['Pattern','Freq_mv3','Accuracy_mv3','Accuracy_mv4']]
df_left_filter_mv3win = df_left_filter[df_left_filter['Accuracy_mv3']>df_left_filter['Accuracy_mv4']]
df_left_filter_mv4win = df_left_filter[df_left_filter['Accuracy_mv3']<df_left_filter['Accuracy_mv4']]
df_on_par = df_left_filter[df_left_filter['Accuracy_mv3']==df_left_filter['Accuracy_mv4']]
print (len(df_left_filter_mv3win),len(df_left_filter_mv4win),len(df_on_par))
df_left_filter_mv4win

131 112 1494

,Pattern,Freq_mv3,Accuracy_mv3,Accuracy_mv4
61,message <relationship_name>,5,0.400000,0.800000
106,hey cortana message <contact_name> on my <orde...,3,0.333333,0.666667
121,message <contact_name> on my <order_ref> meeti...,3,0.666667,1.000000
124,message <contact_name> on <source_platform>,3,0.333333,0.666667
130,message <relationship_name> <message>,3,0.666667,1.000000
145,send a message <relationship_name> <message>,3,0.333333,0.666667
147,send a message <message> to <contact_name>,3,0.333333,0.666667
155,can you send a text message to <relationship_n...,2,0.500000,1.000000
167,cortana send a message to the <contact_name>,2,0.500000,1.000000
170,cortana send <contact_name> <message>,2,0.500000,1.000000
176,cortana send this message to <contact_name>,2,0.500000,1.000000
209,message by <time> meeting,2,0.500000,1.000000
215,message everyone on my <time> meeting <message>,2,0.500000,1.000000
221,message <contact_name> on my <time> meeting,2,0.000000,0.500000
227,message my <relationship_name>,2,0.500000,1.000000
230,message my <meeting_title> meeting that <message>,2,0.000000,1.000000
235,message the <contact_name>,2,0.500000,1.000000
238,message to <meeting_title> meeting,2,0.000000,0.500000
258,send a message from <source_platform>,2,0.000000,1.000000
260,send a message from my <from_relationship_name>,2,0.500000,1.000000
265,send a message through <source_platform>,2,0.500000,1.000000
269,send a message to <contact_name> saying <message>,2,0.500000,1.000000
295,am late for the text <contact_name>,1,0.000000,1.000000
297,and it didn't work. send a message to <contact...,1,0.000000,1.000000
303,ansari message <contact_name>,1,0.000000,1.000000
323,bo send message to <contact_name>,1,0.000000,1.000000
376,can you please send a message back to him that...,1,0.000000,1.000000
383,can you please send a text message to <contact...,1,0.000000,1.000000
411,can you send a message to my <relationship_nam...,1,0.000000,1.000000
418,can you send a message you,1,0.000000,1.000000
...,...,...,...,...
1380,message <contact_name> on my <order_ref> meeti...,1,0.000000,1.000000
1388,message your my <relationship_name>,1,0.000000,1.000000
1391,"message, a meeting",1,0.000000,1.000000
1452,oh ok message message <contact_name>,1,0.000000,1.000000
1468,ok send a message with him,1,0.000000,1.000000
1472,ok so send a message <phone_number>,1,0.000000,1.000000
1474,ok text to <contact_name>,1,0.000000,1.000000
1477,"ok, i will send your message to <contact_name>",1,0.000000,1.000000
1564,please send a message in <source_platform> to ...,1,0.000000,1.000000
1566,please send a message to the meeting for <time>,1,0.000000,1.000000
1567,please send a message to <contact_name> <sourc...,1,0.000000,1.000000
1579,please send please send a message to <contact_...,1,0.000000,1.000000
1592,please text me <message>,1,0.000000,1.000000
1614,reply to all on my <order_ref> meeting that <m...,1,0.000000,1.000000
1627,respond to <contact_name> text,1,0.000000,1.000000
1637,s take a message,1,0.000000,1.000000
1646,schedule to send a text message to <contact_na...,1,0.000000,1.000000
1652,send <phone_number> a message,1,0.000000,1.000000
1653,send <phone_number> message,1,0.000000,1.000000
1662,send <message> a message,1,0.000000,1.000000
1684,send a message at <time>,1,0.000000,1.000000
1689,send a message <message> to <relationship_name>,1,0.000000,1.000000
1695,send a message for <contact_name> for <message>,1,0.000000,1.000000
1697,send a message for him and,1,0.000000,1.000000
1712,send a message <message> on <source_platform>,1,0.000000,1.000000
1713,send a message in <source_platform>,1,0.000000,1.000000
1722,send a message message hey cortana message,1,0.000000,1.000000
1740,send a message that to <contact_name>,1,0.000000,1.000000
1742,send a message through my <source_platform> to...,1,0.000000,1.000000
1767,send a message to anything to,1,0.000000,1.000000

In [41]:
df_left_filter_mv3win

,Pattern,Freq_mv3,Accuracy_mv3,Accuracy_mv4
42,can you text <contact_name>,5,1.000000,0.800000
52,hey cortana message my <time> o&apos;clock mee...,5,1.000000,0.800000
56,"hey cortana, send message to <contact_name>",5,1.000000,0.800000
60,message <contact_name> &apos;s,5,1.000000,0.200000
74,pii:scrubbed:[latency:2]:send a message to <co...,5,1.000000,0.000000
78,send a message to <phone_number>,5,1.000000,0.800000
80,can you text <contact_name> <message>,4,0.750000,0.500000
83,cortana say <message> to <contact_name>,4,0.250000,0.000000
85,hey cortana message <meeting_title> meeting,4,1.000000,0.500000
90,message <contact_name> that,4,1.000000,0.750000
117,hi cortana send <contact_name> a message,3,1.000000,0.666667
129,message <meeting_title> meeting that <message>,3,1.000000,0.333333
131,message my <time> o&apos;clock meeting that <m...,3,1.000000,0.666667
133,message <meeting_title> meeting,3,1.000000,0.666667
143,send <contact_name> a message,3,0.333333,0.000000
149,send a message that <message>,3,1.000000,0.666667
190,hey cortana send a <contact_name> a message,2,1.000000,0.500000
203,<message>,2,0.500000,0.000000
208,message <contact_name> in,2,1.000000,0.500000
228,message <meeting_title> meeting. <message>,2,1.000000,0.500000
229,message my meeting <time>,2,1.000000,0.500000
236,message to <destination_platform>,2,1.000000,0.500000
239,message to <contact_name> saying <message>,2,1.000000,0.500000
274,<message> message,1,1.000000,0.000000
278,a message to <relationship_name>,1,1.000000,0.000000
286,add a lunch message,1,1.000000,0.000000
298,and message everyone on my <time> meeting that...,1,1.000000,0.000000
308,ask <relationship_name> down <message>,1,1.000000,0.000000
324,<relationship_name> text <contact_name>,1,1.000000,0.000000
405,can you send a message to <destination_platform>,1,1.000000,0.000000
...,...,...,...,...
1524,pii:scrubbed:[latency:2]:message everyone on t...,1,1.000000,0.000000
1528,pii:scrubbed:[latency:2]:send a message to eve...,1,1.000000,0.000000
1529,pii:scrubbed:[latency:2]:send a message to my ...,1,1.000000,0.000000
1530,pii:scrubbed:[latency:2]:send a message with <...,1,1.000000,0.000000
1534,pii:scrubbed:[latency:2]:send message to my <t...,1,1.000000,0.000000
1535,pii:scrubbed:[latency:2]:send text message to ...,1,1.000000,0.000000
1550,pii:scrubbed:[latency:7]:send a message to my ...,1,1.000000,0.000000
1568,please send a message um,1,1.000000,0.000000
1573,please send can you send <contact_name> on to ...,1,1.000000,0.000000
1574,please send <contact_name> a text message at <...,1,1.000000,0.000000
1599,please upload a testing message,1,1.000000,0.000000
1618,reply to message on <source_platform>,1,1.000000,0.000000
1647,sedraia message,1,1.000000,0.000000
1659,send a <contact_name> a message telling him <m...,1,1.000000,0.000000
1670,send a invite to <contact_name>,1,1.000000,0.000000
1671,send a is the sink a message,1,1.000000,0.000000
1691,send a message chat hello cortana,1,1.000000,0.000000
1693,send a message draft,1,1.000000,0.000000
1705,send a message from <from_contact_name> by <so...,1,1.000000,0.000000
1708,send a message from my head,1,1.000000,0.000000
1711,send a message hey cortana the message,1,1.000000,0.000000
1719,send a message in <source_platform> in,1,1.000000,0.000000
1724,send a message oh send a message,1,1.000000,0.000000
1727,send a message on <source_platform> to <contac...,1,1.000000,0.000000
1747,send a message to <time> meeting saying <message>,1,1.000000,0.000000
1748,"send a message to <time> meeting, <message>",1,1.000000,0.000000
1756,send a message to <contact_name> that / <message>,1,1.000000,0.000000
1761,send a message to all,1,1.000000,0.000000
1770,send a message to ask <message>,1,1.000000,0.000000
1776,send a message to <meeting_title> meeting,1,1.000000,0.000000